<%@page contentType="text/html" pageEncoding="UTF-8"%> <%@ taglib
uri="/WEB-INF/tlds/ict-taglib" prefix="ict" %>
<ict:checkDbConnection />

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Report - <%= request.getParameter("report") %></title>

        <script src="https://cdn.tailwindcss.com"></script>

        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous">
        </script>

        <link
            href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.2.0/mdb.min.css"
            rel="stylesheet"
        />

        <script src="https://code.jquery.com/jquery-3.6.4.min.js"
        integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>

        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />


        <style>
            .btn-primary {
                background-color: #3b71ca !important;
            }

            .action {
                border: rgba(0, 0, 0, 0.1) 1px solid;
            }

            .action:hover {
                border: #3b71ca 1px solid;
            }
        </style>
    </head>
    <body class="h-screen w-screen overflow-x-hidden">
        <jsp:include page="header.jsp" />

        <div class="content px-5 flex flex-col pb-3 pt-4">
            <div class="flex flex-row align-baseline">
                <div class="title uppercase text-xl font-bold">
                    Analytic / Report
                    <!-- Analytic / Report
                    ● Show a list of booking records of the selected venue
                    ● Show the booking rate of selected venue (calculated by month/year)
                    ● Show the booking attendance rate of selected user (calculated by month/year)
                    ● Show the monthly/ yearly income generated by each venue -->
                    <div class="text-sm font-normal text-gray-500 lowercase">
                        Choose an option below to get started
                    </div>
                </div>
            </div>

            <div class="content mt-4">
                <div class="cards grid grid-cols-4 gap-3 select-none">
                    <a href="<%=request.getContextPath()%>/admin/report.jsp?report=venue" class="text-white">
                        <div class="action card card-body">
                            <div class="text-lg font-bold text-gray-900">
                                Venue
                            </div>
                            <div
                                class="text-sm font-normal text-gray-500 lowercase"
                            >
                                List of booking records of the selected venue
                            </div>
                        </div>
                    </a>
                    <a href="<%=request.getContextPath()%>/admin/report.jsp?report=brate" class="text-white">
                        <div class="action card card-body">
                            <div class="text-lg font-bold text-gray-900">
                                Booking Rate
                            </div>
                            <div
                                class="text-sm font-normal text-gray-500 lowercase"
                            >
                                The booking rate of selected venue
                            </div>
                        </div>
                    </a>
                    <a href="<%=request.getContextPath()%>/admin/report.jsp?report=barate" class="text-white">
                        <div class="action card card-body">
                            <div class="text-lg font-bold text-gray-900">
                                Booking Attendance Rate
                            </div>
                            <div
                                class="text-sm font-normal text-gray-500 lowercase"
                            >
                                The booking attendance rate of selected user
                            </div>
                        </div>
                    </a>
                    <a href="<%=request.getContextPath()%>/admin/report.jsp?report=vincome" class="text-white">
                        <div class="action card card-body">
                            <div class="text-lg font-bold text-gray-900">
                                Veune Income
                            </div>
                            <div
                                class="text-sm font-normal text-gray-500 lowercase"
                            >
                                The monthly / yearly income generated by each
                                venue
                            </div>
                        </div>
                    </a>
                </div>

                <div class="mt-5">
                    <% if (request.getParameter("report") != null) { String
                    report = request.getParameter("report"); if
                    (report.equals("venue")) { %>
                    <jsp:include page="./reports/report_venue.jsp" />
                    <% } else if (report.equals("brate")) { %>
                    <jsp:include page="./reports/report_brate.jsp" />
                    <% } else if (report.equals("barate")) { %>
                    <jsp:include page="./reports/report_barate.jsp" />
                    <% } else if (report.equals("vincome")) { %>
                    <jsp:include page="./reports/report_vincome.jsp" />
                    <% } } %>
                </div>
            </div>
        </div>
        <script>
            // ITP4511_Assignment/api/report
            // {"EPL(Tuen Mun)":{"totalbookings":"12","recent 14 weeks occupancy rate":{"0":"7.142857551574707","11":"0.0","1":"50.0","2":"0.0","3":"0.0","4":"0.0","5":"0.0","6":"0.0","7":"0.0","8":"0.0","9":"0.0","10":"0.0"},"recent 12 months occupancy rate":{"0":"4.34782600402832","11":"0.0","1":"0.0","2":"0.0","3":"0.0","4":"0.0","5":"0.0","6":"0.0","7":"0.0","8":"0.0","9":"0.0","10":"0.0"},"Total Income":"1200.0","recent 14 weeks bookings":{"0":"12","11":"0","1":"0","2":"0","3":"0","4":"0","5":"0","6":"0","7":"0","8":"0","9":"0","10":"0"},"Total Income (weekly)":{"0":"600.0","11":"0.0","1":"600.0","2":"0.0","3":"0.0","4":"0.0","5":"0.0","6":"0.0","7":"0.0","8":"0.0","9":"0.0","10":"0.0"}},"EPL(Sha Tin)":{"totalbookings":"6","recent 14 weeks occupancy rate":{"0":"1.1904761791229248","11":"0.0","1":"41.666664123535156","2":"0.0","3":"0.0","4":"0.0","5":"0.0","6":"0.0","7":"0.0","8":"0.0","9":"0.0","10":"0.0"},"recent 12 months occupancy rate":{"0":"2.17391300201416","11":"0.0","1":"0.0","2":"0.0","3":"0.0","4":"0.0","5":"0.0","6":"0.0","7":"0.0","8":"0.0","9":"0.0","10":"0.0"},"Total Income":"1200.0","recent 14 weeks bookings":{"0":"6","11":"0","1":"0","2":"0","3":"0","4":"0","5":"0","6":"0","7":"0","8":"0","9":"0","10":"0"},"Total Income (weekly)":{"0":"200.0","11":"0.0","1":"1000.0","2":"0.0","3":"0.0","4":"0.0","5":"0.0","6":"0.0","7":"0.0","8":"0.0","9":"0.0","10":"0.0"}},"EPL(Tsing Yi)":{"totalbookings":"8","recent 14 weeks occupancy rate":{"0":"3.5714287757873535","11":"0.0","1":"41.666664123535156","2":"0.0","3":"0.0","4":"0.0","5":"0.0","6":"0.0","7":"0.0","8":"0.0","9":"0.0","10":"0.0"},"recent 12 months occupancy rate":{"0":"2.8985507488250732","11":"0.0","1":"0.0","2":"0.0","3":"0.0","4":"0.0","5":"0.0","6":"0.0","7":"0.0","8":"0.0","9":"0.0","10":"0.0"},"Total Income":"1200.0","recent 14 weeks bookings":{"0":"8","11":"0","1":"0","2":"0","3":"0","4":"0","5":"0","6":"0","7":"0","8":"0","9":"0","10":"0"},"Total Income (weekly)":{"0":"450.0","11":"0.0","1":"750.0","2":"0.0","3":"0.0","4":"0.0","5":"0.0","6":"0.0","7":"0.0","8":"0.0","9":"0.0","10":"0.0"}},"EPL(Lee Wai Lee)":{"totalbookings":"8","recent 14 weeks occupancy rate":{"0":"0.0","11":"0.0","1":"66.66667175292969","2":"0.0","3":"0.0","4":"0.0","5":"0.0","6":"0.0","7":"0.0","8":"0.0","9":"0.0","10":"0.0"},"recent 12 months occupancy rate":{"0":"2.8985507488250732","11":"0.0","1":"0.0","2":"0.0","3":"0.0","4":"0.0","5":"0.0","6":"0.0","7":"0.0","8":"0.0","9":"0.0","10":"0.0"},"Total Income":"600.0","recent 14 weeks bookings":{"0":"8","11":"0","1":"0","2":"0","3":"0","4":"0","5":"0","6":"0","7":"0","8":"0","9":"0","10":"0"},"Total Income (weekly)":{"0":"0.0","11":"0.0","1":"600.0","2":"0.0","3":"0.0","4":"0.0","5":"0.0","6":"0.0","7":"0.0","8":"0.0","9":"0.0","10":"0.0"}},"EPL(Chai Wan)":{"totalbookings":"3","recent 14 weeks occupancy rate":{"0":"0.0","11":"0.0","1":"25.0","2":"0.0","3":"0.0","4":"0.0","5":"0.0","6":"0.0","7":"0.0","8":"0.0","9":"0.0","10":"0.0"},"recent 12 months occupancy rate":{"0":"1.08695650100708","11":"0.0","1":"0.0","2":"0.0","3":"0.0","4":"0.0","5":"0.0","6":"0.0","7":"0.0","8":"0.0","9":"0.0","10":"0.0"},"Total Income":"750.0","recent 14 weeks bookings":{"0":"3","11":"0","1":"0","2":"0","3":"0","4":"0","5":"0","6":"0","7":"0","8":"0","9":"0","10":"0"},"Total Income (weekly)":{"0":"0.0","11":"0.0","1":"750.0","2":"0.0","3":"0.0","4":"0.0","5":"0.0","6":"0.0","7":"0.0","8":"0.0","9":"0.0","10":"0.0"}}}

            let apiLocation = "<%=request.getContextPath()%>" + "/api/report";
            let apiLocation_veune =
                "<%=request.getContextPath()%>" + "/api/report?action=venue";

            async function fetchVenueName() {
                let response = await fetch(apiLocation_veune);
                let data = await response.json();
                return data;
            }

            fetch(apiLocation)
                .then((response) => response.json())
                .then(async (data) => {
                    vname = await fetchVenueName();
                });
        </script>
    </body>
</html>
